# Generated by Django 3.2 on 2021-06-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
