# Generated by Django 3.2 on 2021-06-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_like_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
    ]
